numeromultiplicado=int(input('digite um número inteiro:'))
print('-'*12)
print('{} x  1 = {}'.format(numeromultiplicado, numeromultiplicado * 1))
print('{} x  2 = {}'.format(numeromultiplicado, numeromultiplicado * 2))
print('{} x  3 = {}'.format(numeromultiplicado, numeromultiplicado * 3))
print('{} x  4 = {}'.format(numeromultiplicado, numeromultiplicado * 4))
print('{} x  5 = {}'.format(numeromultiplicado, numeromultiplicado * 5))
print('{} x  6 = {}'.format(numeromultiplicado, numeromultiplicado * 6))
print('{} x  7 = {}'.format(numeromultiplicado, numeromultiplicado * 7))
print('{} x  8 = {}'.format(numeromultiplicado, numeromultiplicado * 8))
print('{} x  9 = {}'.format(numeromultiplicado, numeromultiplicado * 9))
print('{} x 10 = {}'.format(numeromultiplicado, numeromultiplicado * 10))
print('-'*12)